language: php

php:
- 5.4
- 5.5
- 5.6

before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source
- npm install grunt-cli
- npm install grunt-contrib-qunit

script:
- vendor/bin/phpunit -c lib/php/phpunit.xml.dist
- npm test
